file-server-url: "http://localhost:8182"
output-path: "/Users/amitphaltankar/Downloads/large2.json"

server:
  port: 8183

logging:
  level:
    root: INFO
  com:
    amitph: DEBUG
  pattern:
    console: "%d{HH:mm:ss,SSS} - %msg%n"
